version: "2.4"
services:
  mini-server:
    build: .
    restart: no
    container_name: mini-server
  nginx:
    image: nginx:latest
    restart: no
    volumes:
      - ./mapped/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    container_name: nginx